### ISSUE TITLE
Large image is cropped

### ISSUE THREAD

**Issue by dicksonleong** [dicksonleong/GagBook#3]
![image](https://cloud.githubusercontent.com/assets/2051511/3459261/bba6d6d4-020a-11e4-85ed-e01e6fa7e7d3.png)

Large (tall) image is cropped by 9GAG and the is no easy way to get the full image url. Currently, the only possible (and reliable) way is to make a request to the post url (eg. making a request to http://9gag.com/gag/a8WZ6RY with "Accept:" header to "application/json" will get [this response](http://pastebin.com/i08wkfLq)) and parse through the JSON to get the full image url.

**Comment by b0bben** [comment]
I've fixed this in my sailfish port by doing the following:
1. Remove the POST call to 9gag since it just gives you article-items in HTML anyway baked into an JSON array. So just get the regular HTML page, and skip JSON all the same.
2. Any element with class "with-button" is a tall image. Find that element using element.findFirst("div.post-container.with-button")
3. Replace the last part of the URL for the image with "_720b.jpg", since that will always give you the full image
4. PROFIT! ;)

See code here:
https://github.com/b0bben/GagBook/blob/sailfish/src/ninegagrequest.cpp#L114

**Comment by dicksonleong** [comment]
That is still consider hard coding the url. Check out [this](http://9gag.com/gag/aAYjy0R), the image url is http://d3dsacqprgcsqh.cloudfront.net/photo/aAYjy0R_700b_v1.jpg. That means their image url is very dynamic and should not be hard code.

**Comment by b0bben** [comment]
http://d3dsacqprgcsqh.cloudfront.net/photo/aAYjy0R_700b.jpg also works :)

I see what you're getting at, and I understand it, I really do. Problem is, we're dealing with web scraping here, and sometimes you have to do stuff like this :)
In my eyes, this is an acceptable solution, since we've found a pattern in the way 9gag serves their tall images, and we should use that.

I'm not aware of any other way to get the image :/

**Comment by dicksonleong** [comment]
Hmm, fair enough. Fixed for harmattan/symbian build as well (240d1d91558c6a29be5ee2ea61dc604343bc840d).
